{ config, pkgs, ... }:

{
  # Framework workstation specific config

  # Imports
  imports =
    [ 
      # Include framework hardware quirks
      <nixos-hardware/framework/13-inch/7040-amd>

      # Home manager - dotfiles
      <home-manager/nixos>
    ];

  # Use flakes
  nix = {
    #package = pkgs.nixFlakes; # dropped with pkg 24.11
    extraOptions = ''
        experimental-features = nix-command flakes
    '';
  };

  # /Boot installation
  boot = {
    loader= {
      grub = {
       theme = "${pkgs.catppuccin-grub}/theme.txt"; # Set a specific installed GRUB theme
      };
    };

    # Initial RamDisk config supplementation - Mostly generated by nixos-generate-config
    initrd = {
      kernelModules = [ "amdgpu" ]; # Load the AMD GPU module
    };

    # Kernel
    kernelModules = [ "kvm-amd" ]; # KVM = Kernel-based Virtual machine -> set kernel up as a hypervisor
    kernelParams = [

      # CPU and performance settings
      "cpufreq.default_governor=powersave"  # Set default CPU governor to powersave for power efficiency
      "initcall_blacklist=cpufreq_gov_userspace_init,cpufreq_gov_performance_init"  # Blacklist CPU frequency governors during initialization

      # AMD settings
      "amd_iommu=off"                 # Disable AMD IOMMU for troubleshooting
      "amd_pstate=active"             # CPU Performance scaling driver active/passive/guided
      "amdgpu.sg_display=0"           # AMD GPU: Disable display signaling
      "amdgpu.abmlevel=3"             # AMD GPU: Adaptive brightness level (0=off, 1-4)

      # Power management settings
      "ie_aspm.policy=powersupersave" # PCIe ASPM policy for power savings
      "pcie_aspm=force"               # Force PCIe ASPM (Active State Power Management) for power savings

      # System debugging and logging
      "rd.udev.log_level=3"           # Set udev logging level
      "udev.log_priority=3"           # Set udev log priority
    ];
  };

  networking = {
    hostName = "Framework-workstation";
  };

  # Enable Docker
  virtualisation = {
    docker.enable = true;
  };

 # Services
  services = {
    gvfs.enable = true; # Gnome virtual file system
    fprintd.enable = true; # Print daemon
    fwupd.enable = true; # Framework specific firmware update tool
    fwupd.extraRemotes = [ "lvfs-testing" ]; # Some framework firmware is still in testing
    flatpak.enable = true; # flatpak.org
    libinput.enable = true; # Touchpad

    displayManager.autoLogin.enable = true;
    displayManager.autoLogin.user = "user";

    pulseaudio.enable = false;
 
    # X11
    xserver = {
      enable = true;
      xkb.layout = "us"; # Keyboard layout
      xkb.variant = ""; # Keyboard
      videoDrivers = [ "amdgpu" ];
      displayManager = {
        lightdm.enable = true;
        lightdm.greeters.gtk = {
          theme.name = "Nordic-darker";
          iconTheme.name = "Nordzy-cyan-dark";
          cursorTheme.name = "Nordzy-cursors"; 
        };
      };
    };

    # Bluetooth
    blueman = {
      enable = true;
    };

  };

  # Hardware-specific configuration
  hardware = {
      bluetooth.enable = true; # Enables support for Bluetooth
      bluetooth.powerOnBoot = true; # Powers up the default Bluetooth controller on boot
  };

  # Users
  users.users.user = {
    isNormalUser = true;
    uid = 1000;
    home = "/home/user";
    description = "user";
    shell = pkgs.fish;
    extraGroups = [
      "docker"
      "networkmanager"
      "storage" 
      "wheel"
    ];
    packages = with pkgs; [

      gimp
      firefox-esr # Firefox extended support branch
      vscode # IDE
      vlc
      kdePackages.kdenlive # Video editor
      keepassxc # Password manager
      signal-desktop # Secure messaging application
      discord # group messaging app
      libreoffice # Office software suite
      librewolf # Firefox fork
      thunderbird # Email client
      obsidian # Note-taking application

    ];
  };

  # Program modules and settings
  programs = {
    hyprland.enable = true; # Dynamic tiling Wayland compositor

    # ClI Editor
    neovim = {
      enable = true;
      defaultEditor = true;
    };

    # Steam
    steam = {
      enable = true;
      remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
      dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
    };

    # Virtualisation tool
    virt-manager = {
      enable = false;
    };
    
    # Fish
    fish = {
     enable = true;
    }; 
  };

  # Nix.PKGs settings
  nixpkgs.config = {
    permittedInsecurePackages = [];
  };

  environment = {
   variables = {
       EDITOR = "nvim";
       XDG_CONFIG_HOME = "$HOME/.config";
       NIXOS_OZONE_WL = "1"; # Wayland compositor adapter for chromium and electron based apps
     };
   systemPackages = with pkgs; [

    # Gnome Desktop
    gnome-applets # Applets for use with the GNOME panel
    gnome-backgrounds # Default wallpaper set for GNOME
    gnome-bluetooth # Bluetooth in the GNOME desktop
    gnome-boxes # Simple GNOME 3 application to access remote or virtual systems
    gnome-calculator # Application that solves mathematical equations and is suitable as a default application in a Desktop environment
    gnome-calendar # Simple and beautiful calendar application for GNOME
    gnome-characters # Simple utility application to find and insert unusual characters
    gnome-connections # Remote desktop client for the GNOME desktop environment
    gnome-console # Simple user-friendly terminal emulator for the GNOME desktop
    gnome-contacts # GNOME’s integrated address book
    gnome-control-center # Utilities to configure the GNOME desktop
    gnome-decoder # Scan and Generate QR Codes
    gnome-disk-utility # Udisks graphical front-end
    gnome-feeds # RSS/Atom feed reader for GNOME
    gnome-firmware # Tool for installing firmware on devices
    gnome-font-viewer # Program that can preview fonts and create thumbnails for fonts
    gnome-icon-theme # Collection of icons for the GNOME 2 desktop
    gnome-keyring # Collection of components in GNOME that store secrets, passwords, keys, certificates 
    gnome-keysign # GTK/GNOME application to use GnuPG for signing other peoples’ keys
    gnome-logs # Log viewer for the systemd journal
    gnome-maps # Map application for GNOME 3
    gnome-menus # Library that implements freedesktops's Desktop Menu Specification in GNOME
    gnome-mines # Clear hidden mines from a minefield
    gnome-multi-writer # Tool for writing an ISO file to multiple USB devices at once
    gnome-music # Music player and management application for the GNOME desktop environment
    gnome-nettool # Collection of networking tools
    gnome-network-displays # Miracast implementation for GNOME
    gnome-notes # Note editor designed to remain simple to use
    gnome-obfuscate # Censor private information
    gnome-photos # Access, organize and share your photos
    gnome-podcasts # Listen to your favorite podcasts
    gnome-power-manager # View battery and power statistics provided by UPower
    gnome-remote-desktop # GNOME Remote Desktop server
    gnome-screenshot # Utility used in the GNOME desktop environment for taking screenshots
    gnome-secrets # Password manager for GNOME which makes use of the KeePass v.4 format
    gnome-session # GNOME session manager
    gnome-shell # Core user interface for the GNOME 3 desktop
    gnome-sound-recorder # Simple and modern sound recorder
    gnome-sudoku # Test your logic skills in this number grid puzzle
    gnome-system-monitor # System Monitor shows you what programs are running and how much processor time, memory, and disk space are being used
    gnome-tecla # Keyboard layout viewer
    gnome-terminal # GNOME Terminal Emulator
    gnome-text-editor # Text Editor for GNOME
    gnome-tweaks # Tool to customize advanced GNOME 3 options
    gnome-usage # Nice way to view information about use of system resources, like memory and disk space
    gnome-video-effects # Collection of GStreamer effects to be used in different GNOME Modules
    gnome-weather # Access current weather conditions and forecasts
    nautilus # File manager for GNOME desktop environment
    snapshot # gnome camera app
    gpick # Advanced color picker written in C++ using GTK+ toolkit
    gcolor3 # Simple color chooser written in GTK3

    # Other
    rpi-imager
    rpiboot
    bitcomet

    # Pulse Audio related
    pavucontrol # GUI for PulseAudio volume control
    pamixer # Command line tool for controlling PulseAudio

    # Terminal and command-line tools
    btop # Monitor of resources
    kitty # Terminal emulator
    tmux # Terminal multiplexer
    vim # CLI text editor
    wget # Tool for downloading files
    
    # Desktop notifications
    dunst # Desktop notification daemon
    libnotify # Library for sending desktop notifications

    # Themes and graphical user interface (GUI) tools
    gtk3 # GUI toolkit
    gtk4 # GUI toolkit
    catppuccin-grub # Grub, the GRand Unified Bootloader theme 
    
    # System and network administration
    burpsuite # Proxy attack tool
    binwalk # Tool for searching a given binary image for embedded files
    d-spy # D-Bus exploration tool
    dnspeep # Spy on the DNS queries your computer is making
    docker # Container platform
    docker-compose # Tool for defining and running multi-container Docker applications
    kubectl # Kubernetes cluster control
    kubernetes-helm # Kubernetes package manager
    lynis # Audit system
    networkmanagerapplet # GUI applet for NetworkManager
    nmap # Network scanner/mapper
    ncdu # Tool for analyzing disk usage
    openvpn
    traceroute
    wireshark # Network protocol analyzer
    #wireguard # vpn
    wireguard-tools # vpn

    # Development tools and frameworks
    git # Version control system
    gcc # C compiler
    gnumake # GNU make tool
    cmake # Build tool
    jq # Command line JSON processor
    python3Full # Python 3 programming language including standard libraries
    lua # Lua programming language
    stow # Tool for managing symlinks in a directory tree
    v4l-utils # Video4Linux utilities
    xdg-desktop-portal-gtk # Implementation of xdg-desktop-portal for GTK
    xdg-desktop-portal-hyprland # Implementation of xdg-desktop-portal for Hyprland
    xdg-utils # Toolset for working with the desktop environment
    
    # Wayland/Desktop-related tools
    wbg # Wallpaper application for Wayland compositors
    wayland-protocols # Common protocols for Wayland
    wayland-utils # Tools for working with Wayland
    wl-clipboard # Command-line copy/paste utilities for Wayland
    rofi-wayland # Application and window switcher for Wayland
    waybar # Highly customizable Wayland bar for your desktop
    wlroots # Modular Wayland compositor library
    xwayland # Xserver for running X11 apps
    brightnessctl # Tool for controlling brightness in Wayland
    
    # CLI Tools
    bat # Syntax highlighting and Git integration for cat
    curl # Tool for transferring data to or from a server
    dig # Tool for querying DNS data
    dmidecode # Tool for reading information from the BIOS
    htop # Interactive system monitor
    killall # Tool for stopping processes
    kubectl # Kubernetes cluster control
    polkit # Tool for bringing up authentication dialogues
    tree # Command to produce a depth indented directory listing

    # Fish plugins
    fishPlugins.z
    fishPlugins.done
    fishPlugins.sponge
    fishPlugins.autopair
    fishPlugins.git-abbr
    fishPlugins.fish-you-should-use

  ];
 };
  
  # Fonts
  fonts.packages = with pkgs; [
    powerline-fonts
    powerline-symbols
  ];
}
